### GET
GET http://localhost:8080/customers

### GET by Id
GET http://localhost:8080/customers/1


### POST
POST http://localhost:8080/customers
Content-Type: application/json

{
  "firstName": "Jonny",
  "lastName": "Cash",
  "email": "jc@email.com"
}

### PUT

PUT http://localhost:8080/customers/1
Content-Type: application/json

{
    "firstName": "Jack",
    "lastName": "Bauer",
    "email": "jack.bauer@example.com"
}

### DELETE By Id
DELETE http://localhost:8080/customers/1
